<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>$(exapiPackage)\</OutputPath>
  </PropertyGroup>
  <ItemGroup Condition="'$(SolutionName)' == 'ExileApi'">
    <ProjectReference Include="..\..\..\Core\Core.csproj" />
  </ItemGroup>
	<ItemGroup Condition="'$(SolutionName)' != 'ExileApi'">
		<Reference Include="ExileCore">
			<HintPath>$(exapiPackage)\ExileCore.dll</HintPath>
			<Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
