<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>

		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

		<!-- Default -->
		<PoeVersion>poe1</PoeVersion>
	</PropertyGroup>

	<!-- Compile-time symbols and output root -->
	<PropertyGroup Condition="'$(PoeVersion)' == 'poe1'">
		<DefineConstants>$(DefineConstants);POE1</DefineConstants>
		<CorePackage>$(exapiPackage)</CorePackage>
		<OutputPath>$(exapiPackage)\</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(PoeVersion)' == 'poe2'">
		<DefineConstants>$(DefineConstants);POE2</DefineConstants>
		<CorePackage>$(exilecore2Package)</CorePackage>
		<OutputPath>$(exilecore2Package)\</OutputPath>
	</PropertyGroup>

	<!-- PoE1 references -->
	<ItemGroup Condition="'$(PoeVersion)' == 'poe1'">
		<Reference Include="ExileCore">
			<HintPath>$(CorePackage)\ExileCore.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<!-- PoE2 references -->
	<ItemGroup Condition="'$(PoeVersion)' == 'poe2'">
		<Reference Include="ExileCore2">
			<HintPath>$(CorePackage)\ExileCore2.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>
